/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AzmoonRouteImport } from './routes/azmoon'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TatbiqRouteImport } from './routes/tatbiq'
import { Route as VajenamehRouteImport } from './routes/vajenameh'
import { Route as YaddashtRouteImport } from './routes/yaddasht'
import { Route as AzmoonJameRouteImport } from './routes/azmoon.jame'
import { Route as BabIdRouteImport } from './routes/bab.$id'
import { Route as MNRouteImport } from './routes/m.$n'
import { Route as AzmoonBabIdRouteImport } from './routes/azmoon.bab.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AzmoonRoute = AzmoonRouteImport.update({
  id: '/azmoon',
  path: '/azmoon',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TatbiqRoute = TatbiqRouteImport.update({
  id: '/tatbiq',
  path: '/tatbiq',
  getParentRoute: () => rootRouteImport,
} as any)
const VajenamehRoute = VajenamehRouteImport.update({
  id: '/vajenameh',
  path: '/vajenameh',
  getParentRoute: () => rootRouteImport,
} as any)
const YaddashtRoute = YaddashtRouteImport.update({
  id: '/yaddasht',
  path: '/yaddasht',
  getParentRoute: () => rootRouteImport,
} as any)
const AzmoonJameRoute = AzmoonJameRouteImport.update({
  id: '/jame',
  path: '/jame',
  getParentRoute: () => AzmoonRoute,
} as any)
const BabIdRoute = BabIdRouteImport.update({
  id: '/bab/$id',
  path: '/bab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MNRoute = MNRouteImport.update({
  id: '/m/$n',
  path: '/m/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const AzmoonBabIdRoute = AzmoonBabIdRouteImport.update({
  id: '/bab/$id',
  path: '/bab/$id',
  getParentRoute: () => AzmoonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azmoon': typeof AzmoonRouteWithChildren
  '/search': typeof SearchRoute
  '/tatbiq': typeof TatbiqRoute
  '/vajenameh': typeof VajenamehRoute
  '/yaddasht': typeof YaddashtRoute
  '/azmoon/jame': typeof AzmoonJameRoute
  '/bab/$id': typeof BabIdRoute
  '/m/$n': typeof MNRoute
  '/azmoon/bab/$id': typeof AzmoonBabIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azmoon': typeof AzmoonRouteWithChildren
  '/search': typeof SearchRoute
  '/tatbiq': typeof TatbiqRoute
  '/vajenameh': typeof VajenamehRoute
  '/yaddasht': typeof YaddashtRoute
  '/azmoon/jame': typeof AzmoonJameRoute
  '/bab/$id': typeof BabIdRoute
  '/m/$n': typeof MNRoute
  '/azmoon/bab/$id': typeof AzmoonBabIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azmoon': typeof AzmoonRouteWithChildren
  '/search': typeof SearchRoute
  '/tatbiq': typeof TatbiqRoute
  '/vajenameh': typeof VajenamehRoute
  '/yaddasht': typeof YaddashtRoute
  '/azmoon/jame': typeof AzmoonJameRoute
  '/bab/$id': typeof BabIdRoute
  '/m/$n': typeof MNRoute
  '/azmoon/bab/$id': typeof AzmoonBabIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azmoon'
    | '/search'
    | '/tatbiq'
    | '/vajenameh'
    | '/yaddasht'
    | '/azmoon/jame'
    | '/bab/$id'
    | '/m/$n'
    | '/azmoon/bab/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azmoon'
    | '/search'
    | '/tatbiq'
    | '/vajenameh'
    | '/yaddasht'
    | '/azmoon/jame'
    | '/bab/$id'
    | '/m/$n'
    | '/azmoon/bab/$id'
  id:
    | '__root__'
    | '/'
    | '/azmoon'
    | '/search'
    | '/tatbiq'
    | '/vajenameh'
    | '/yaddasht'
    | '/azmoon/jame'
    | '/bab/$id'
    | '/m/$n'
    | '/azmoon/bab/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzmoonRoute: typeof AzmoonRouteWithChildren
  SearchRoute: typeof SearchRoute
  TatbiqRoute: typeof TatbiqRoute
  VajenamehRoute: typeof VajenamehRoute
  YaddashtRoute: typeof YaddashtRoute
  BabIdRoute: typeof BabIdRoute
  MNRoute: typeof MNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azmoon': {
      id: '/azmoon'
      path: '/azmoon'
      fullPath: '/azmoon'
      preLoaderRoute: typeof AzmoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tatbiq': {
      id: '/tatbiq'
      path: '/tatbiq'
      fullPath: '/tatbiq'
      preLoaderRoute: typeof TatbiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vajenameh': {
      id: '/vajenameh'
      path: '/vajenameh'
      fullPath: '/vajenameh'
      preLoaderRoute: typeof VajenamehRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaddasht': {
      id: '/yaddasht'
      path: '/yaddasht'
      fullPath: '/yaddasht'
      preLoaderRoute: typeof YaddashtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azmoon/jame': {
      id: '/azmoon/jame'
      path: '/jame'
      fullPath: '/azmoon/jame'
      preLoaderRoute: typeof AzmoonJameRouteImport
      parentRoute: typeof AzmoonRoute
    }
    '/bab/$id': {
      id: '/bab/$id'
      path: '/bab/$id'
      fullPath: '/bab/$id'
      preLoaderRoute: typeof BabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$n': {
      id: '/m/$n'
      path: '/m/$n'
      fullPath: '/m/$n'
      preLoaderRoute: typeof MNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azmoon/bab/$id': {
      id: '/azmoon/bab/$id'
      path: '/bab/$id'
      fullPath: '/azmoon/bab/$id'
      preLoaderRoute: typeof AzmoonBabIdRouteImport
      parentRoute: typeof AzmoonRoute
    }
  }
}

interface AzmoonRouteChildren {
  AzmoonJameRoute: typeof AzmoonJameRoute
  AzmoonBabIdRoute: typeof AzmoonBabIdRoute
}

const AzmoonRouteChildren: AzmoonRouteChildren = {
  AzmoonJameRoute: AzmoonJameRoute,
  AzmoonBabIdRoute: AzmoonBabIdRoute,
}

const AzmoonRouteWithChildren =
  AzmoonRoute._addFileChildren(AzmoonRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzmoonRoute: AzmoonRouteWithChildren,
  SearchRoute: SearchRoute,
  TatbiqRoute: TatbiqRoute,
  VajenamehRoute: VajenamehRoute,
  YaddashtRoute: YaddashtRoute,
  BabIdRoute: BabIdRoute,
  MNRoute: MNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
